---
tags: [spring-data, jpa]
projects: [spring-data-jpa]
---
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-accessing-data-jpa
本指南会通过带你一步一步创建一个应用程序，这个应用程序使用Spring Data JPA在关系数据库中存储和检索数据。

== 你将做出什么

你将构建一个应用，它会保存 `Customer` link:/understanding/POJO[POJOs] (简单Java对象)到内存数据库中。

== 你需要什么

:java_version: 1.8
include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/hide-show-sts.adoc[]


[[initial]]
== 定义一个简单实体

在这个例子中，你需要保存一个被标记为JPA实体的Customer对象。

`src/main/java/hello/Customer.java`
[source,java,indent=0]
----
include::complete/src/main/java/hello/Customer.java[tag=sample]
}
----

这样你就有了一个带有 `id` 、`firstName`、`lastName`三个属性的 `Customer` 类。另外还有两个构造器。默认的（第一个）构造函数只为了提供给JPA使用，你不会直接用到它，所以他被声明为protected。另一个构造器就是你用来创建Customer实例并存入数据库的。

NOTE: 在本指南中，getter和setter都因篇幅限制而省略

`Customer` 类被标注了 `@Entity` 注解来声明这是个JPA实体。因为缺少一个显式的@ `@Table` 注解，根据约定这个实体会被映射到名为 `Customer` 的表中。

`Customer` 类的id属性被标注了 `@Id` 注解，这样JPA会知道这是对象的ID。 `id` 属性同样被标注了 `@GeneratedValue` 注解来向JPA声明这个对象的ID应该被自动生成。

另外两个属性 `firstName` 和 `lastName` 没被标注。根据约定这两个属性将被映射为Customer表和他们同名的的列。

最后， `toString()` 方法提供了一个很方便的方式将Customer的属性打印出来。

== 创建一个简单的查询
Spring Data JPA聚焦在使用JPA保存数据到关系数据库。它最引人瞩目的特点是具有在运行时通过repository api自动创建repository的实现的能力。

为了看到它们如何工作，我们来创建一个与 `Customer` 实体一起工作的repository:

`src/main/java/hello/CustomerRepository.java`
[source,java]
----
include::complete/src/main/java/hello/CustomerRepository.java[]
----
    
`CustomerRepository` 扩展了 `CrudRepository` 。 `Customer` 和 `Long` 作为实体和id的传递给了 `CrudRepository` 。通过扩展 `CrudRepository` ， `CustomerRepository`继承了多个方法来完成 `Customer` 的持久化工作，其中包括保存、删除和寻找 `Customer` 实体。

Spring Data JPA 还可以通过简单地声明他们的方法签名定义其他的查询方法。就像在这个`CustomerRepository` 中的 `findByLastName()` 方法一样。

在一个典型Java应用程序中，你会需要写一个 `CustomerRepository` 类的实现。但这也是Spring Data JPA 的强大之处：现在你不需要再根据这个repository接口写一个CustomerRepository类的实现了。Spring Data JPA在会运行程序时为你做这些事。

让我们把他们连接起来看看怎么样!

== 创建Application类
现在你要创建一个Application类，带上其他所有的组件。

`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/spring-boot-application.adoc[]

`Application` 类包括了一个 `main()` 函数，并加入了一些测试数据到 `CustomerRepository` 中。首先它从应用上下文中获取到 `CustomerRepository` ，然后它通过展示 `save()` 方法，创建了一些测试数据，来保存了几个 `Customer` 对象。然后调用 `findAll()` 来从数据库中获得所有的Customer对象。接着调用 `findOne()` 来通过ID获取一个单独的 `Customer` 对象。最后，它调用 `findByLastName()` 方法找到了所有lastName 为 "Bauer" 的Customer对象。

NOTE: 默认情况下，Spring Boot会启用JPA repository支持，并扫描package（和他的下级package）来确认 `@SpringBootApplication` 的位置。如果你在一些不可见的package中配置有JPA repository 接口的定义，你可以用@EnableJpaRepositories注解，和他的类型安全的参数.

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/build_an_executable_jar_mainhead.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]
    
    
你将会看到这样的输出：
....
== Customers found with findAll():
Customer[id=1, firstName='Jack', lastName='Bauer']
Customer[id=2, firstName='Chloe', lastName='O'Brian']
Customer[id=3, firstName='Kim', lastName='Bauer']
Customer[id=4, firstName='David', lastName='Palmer']
Customer[id=5, firstName='Michelle', lastName='Dessler']

== Customer found with findOne(1L):
Customer[id=1, firstName='Jack', lastName='Bauer']

== Customer found with findByLastName('Bauer'):
Customer[id=1, firstName='Jack', lastName='Bauer']
Customer[id=3, firstName='Kim', lastName='Bauer']
....

== Summary
恭喜，你已经写出了一个简单的使用Spring Data JPA来保存、取出对象的应用——关于repository的实现，一点代码也没有。

NOTE: 如果你对暴露JPA在超媒体的RESTful前段下感兴趣，你可能会想阅读 link:/guides/gs/accessing-data-rest[用REST访问JPA数据].

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/footer.adoc[]

